[package]
name = "rootproof-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }

tokio = { version = "1", features = ["macros","rt-multi-thread"]}
rootproof-core = { path = "../rootproof-core" }
rootproof-language = { path = "../rootproof-language" }